//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaGearWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GearStore
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int Strength { get; set; }
        public int Intelligence { get; set; }
        public int Agility { get; set; }
        public int Gold { get; set; }
    
        public virtual Gear Gear { get; set; }
    }
}
